// ===== ข้อมูลตัวอย่าง (mock) สำหรับทดลองหน้าตา ก่อนเชื่อม Supabase จริง =====
import type { Contract, Option, Shop } from './types'

export const shops: Shop[] = [
  {
    id: 's16',
    code: 'AQ S00016',
    name: 'ร้านมาดามศิโมบาย',
    bank: 'ธนาคารกสิกร',
    accountNo: '2302882749',
    accountName: 'บจก มาดามศิ อินเตอร์กรุ๊ป',
    active: true,
  },
  {
    id: 's17',
    code: 'AQ S00017',
    name: 'ร้านซีเดย์โฟน',
    bank: 'ธนาคาร ธกส',
    accountNo: '20036139987',
    accountName: 'วิทยา ธิพงษ์สันต์',
    active: true,
  },
]

export const phoneModels: Option[] = [
  { id: 'm1', label: 'iPhone 13', active: true },
  { id: 'm2', label: 'iPhone 13 Pro Max', active: true },
  { id: 'm3', label: 'iPhone 14', active: true },
  { id: 'm4', label: 'iPhone 14 Pro', active: true },
  { id: 'm5', label: 'iPhone 14 Pro Max', active: true },
  { id: 'm6', label: 'iPhone 15 Plus', active: true },
  { id: 'm7', label: 'iPhone 16 Pro', active: true },
]

export const storageOptions: Option[] = [
  { id: 'st1', label: '128 GB', active: true },
  { id: 'st2', label: '256 GB', active: true },
  { id: 'st3', label: '512 GB', active: true },
]

export const occupations: Option[] = [
  { id: 'o1', label: 'พนักงานประจำ', active: true },
  { id: 'o2', label: 'ค้าขาย', active: true },
  { id: 'o3', label: 'รับจ้าง', active: true },
  { id: 'o4', label: 'เกษตรกร', active: true },
]

export const occupationProofs: Option[] = [
  { id: 'p1', label: 'สลิปเงินเดือน', active: true },
  { id: 'p2', label: 'บัตรประชาชน', active: true },
  { id: 'p3', label: 'รูปถ่ายกิจการ', active: true },
]

export const promotions: Option[] = [
  { id: 'pr1', label: 'ไม่มีโปร', active: true },
  { id: 'pr2', label: 'ฟรีเคส+ฟิล์ม', detail: 'แถมเคสและฟิล์มกันรอย', active: true },
  { id: 'pr3', label: 'ดาวน์ 0 เดือนแรก', detail: 'ผ่อนเดือนแรกเริ่มเดือนถัดไป', active: true },
]

export const contracts: Contract[] = [
  {
    id: 'c1',
    contractNo: 'S00016PNQ280',
    invNo: 'INV-17794517622120',
    sn: 'J12GJVQT7J',
    customerName: 'น.ส.ภัทราภรณ์ พึ่งสละ',
    phone: '0900271569',
    shopId: 's16',
    model: 'iPhone 13 Pro Max',
    storage: '256 GB',
    condition: 'new',
    origin: 'th',
    devicePrice: 19900,
    downPercent: 30,
    commissionPercent: 12,
    docFee: 100,
    financeAmount: 13930,
    monthlyPayment: 1912,
    termMonths: 12,
    dueDay: 23,
    hasPromotion: false,
    status: 'active',
    transactionDate: '2026-05-22',
    operator: 'พนักงาน A',
    birthYear: 1998,
    occupation: 'พนักงานประจำ',
    occupationProof: 'สลิปเงินเดือน',
    summarySentAt: null,
    emailSentAt: null,
  },
  {
    id: 'c2',
    contractNo: 'S00017PNQ149',
    invNo: 'INV-17790264179507',
    sn: 'D1740QDQQ3',
    customerName: 'นาย รัชพล นวลหลำ',
    phone: '0941464938',
    shopId: 's17',
    model: 'iPhone 15 Plus',
    storage: '128 GB',
    condition: 'new',
    origin: 'th',
    devicePrice: 22900,
    downPercent: 30,
    commissionPercent: 12,
    docFee: 100,
    financeAmount: 16030,
    monthlyPayment: 1924,
    termMonths: 12,
    dueDay: 2,
    hasPromotion: false,
    status: 'active',
    transactionDate: '2026-05-18',
    operator: 'พนักงาน B',
    birthYear: 1995,
    occupation: 'ค้าขาย',
    occupationProof: 'บัตรประชาชน',
    summarySentAt: null,
    emailSentAt: '2026-05-18',
  },
  {
    id: 'c3',
    contractNo: 'S00016PNQ276',
    invNo: 'INV-17790257668410',
    sn: 'LL7Q72QHXR',
    customerName: 'น.ส.เสาวลักษณ์ อ่อนสะเดา',
    phone: '0900634798',
    shopId: 's16',
    model: 'iPhone 14 Pro',
    storage: '128 GB',
    condition: 'used',
    origin: 'th',
    devicePrice: 18900,
    downPercent: 30,
    commissionPercent: 12,
    docFee: 100,
    financeAmount: 13230,
    monthlyPayment: 1100,
    termMonths: 12,
    dueDay: 31,
    hasPromotion: true,
    promotion: 'ฟรีเคส+ฟิล์ม',
    promotionDetail: 'แถมเคสและฟิล์มกันรอย',
    status: 'active',
    transactionDate: '2026-03-31',
    operator: 'พนักงาน A',
    birthYear: 1990,
    occupation: 'รับจ้าง',
    occupationProof: 'บัตรประชาชน',
    summarySentAt: '2026-05-18',
    emailSentAt: '2026-05-18',
  },
]
